dist: xenial
language: node_js
node_js:
  - '12.4'

install:
  - yarn install

cache:
  yarn: true
  directories:
    - node_modules

stages:
  - lint
  - test

services: postgresql

env:
  - GOOGLE_CONSUMER_KEY=google GOOGLE_CONSUMER_SECRET=google JWT_SECRET=jwt REDIS_URL=''

jobs:
  include:
    - stage: lint
      script: yarn prettier:check

    - stage: test
      script: yarn build

    - stage: test
      before_script: psql -c 'create database test;' -U postgres
      script: yarn test

