default: &default
  type: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: postgres
  synchronize: true
  logging: true
  entities:
    - src/entities/**.ts
  migrations:
    - src/migration/**.ts
  subscribers:
    - src/subscriber/**.ts
  cli:
    entitiesDir: src/entities
    migrationsDir: src/migration
    subscribersDir: src/subscriber


test:
  <<: *default
  database: test
  logging: false
  dropSchema: true
