version: 2
jobs:
  build:
    docker:
      - image: circleci/node
      - image: postgres

    steps:
      - checkout
      - run:
          name: get-yarn
          command: sudo npm install -g yarn
      - restore_cache: # Get cache based on node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  lint:
    requires:
      - build
    steps:
      - command: yarn lint

