export interface OpenFoodFactProductNutriments {
  carbohydrates_unit: string;
  fiber: number;
  salt_value: string | number;
  fat_value: string | number;
  proteins_value: string | number;
  'nova-group': string | number;
  'nova-group_100g': string | number;
  sugars_100g: string | number;
  sugars_serving: string | number;
  'nutrition-score-uk': string | number;
  'saturated-fat_unit': string;
  fiber_unit: string;
  sugars_unit: string;
  fat_serving: string | number;
  energy_unit: string;
  fiber_serving: string | number;
  salt_unit: string;
  energy_100g: string | number;
  proteins_unit: string;
  salt_serving: string | number;
  energy: string | number;
  energy_value: string | number;
  sugars: string | number;
  fiber_value: string | number;
  fiber_100g: string | number;
  salt_100g: string | number;
  'nova-group_serving': string | number;
  energy_serving: string | number;
  sodium_unit: string;
  sugars_value: string | number;
  fat_100g: string | number;
  'nutrition-score-fr': string | number;
  'saturated-fat_serving': string | number;
  carbohydrates: string | number;
  proteins_serving: string | number;
  'saturated-fat_100g': string | number;
  carbohydrates_serving: string | number;
  'nutrition-score-fr_100g': string | number;
  salt: string | number;
  sodium_serving: string | number;
  proteins: string | number;
  carbohydrates_100g: string | number;
  sodium_value: string | number;
  fat_unit: string;
  'saturated-fat_value': string | number;
  carbohydrates_value: string | number;
  fat: string | number;
  sodium_100g: string | number;
  'nutrition-score-uk_100g': string | number;
  sodium: string | number;
  'saturated-fat': string | number;
  proteins_100g: string | number;
}

export interface OpenFoodFactProduct {
  nutrition_data_per: string;
  last_edit_dates_tags: string[];
  emb_codes: string;
  purchase_places_debug_tags: string;
  brands_tags: string[];
  editors_tags: string[];
  image_thumb_url: string;
  serving_size: string;
  additives_old_n: number;
  last_image_dates_tags: string[];
  allergens: string;
  unknown_ingredients_n: number;
  correctors_tags: string[];
  categories_hierarchy: string[];
  allergens_hierarchy: string[];
  nutriments: OpenFoodFactProductNutriments;
  unknown_nutrients_tags: string[];
  ingredients_debug: (string | null)[];
  minerals_prev_tags: string;
  generic_name_fr: string;
  pnns_groups_2_tags: string[];
  traces_debug_tags: (string | null)[];
  no_nutrition_data: string;
  states_tags: string[];
  additives_old_tags: string[];
  nutrient_levels_tags: string[];
  product_name: string;
  product_name_fr_debug_tags: (string | null)[];
  ingredients_that_may_be_from_palm_oil_n: number;
  image_ingredients_url: string;
  image_url: string;
  ingredients_that_may_be_from_palm_oil_tags: string[];
  countries: string;
  codes_tags: string[];
  ingredients_text_with_allergens: string;
  origins: string;
  ingredients_from_palm_oil_n: number;
  countries_tags: string[];
  image_front_url: string;
  selected_images: { front: object, ingredient: object, nutrition: object };
  ingredients_text_debug: string;
  allergens_debug_tags: (string | null)[];
  origins_tags: string[];
  ingredients_n: number;
  states: string;
  update_key: string;
  expiration_date: string;
  photographers_tags: string[];
  completed_t: number;
  packaging_debug_tags: (string | null)[];
  allergens_from_user: string;
  max_imgid: string;
  additives_original_tags: string[];
  informers_tags: string[];
  code: string;
  image_front_thumb_url: string;
  quantity_debug_tags: (string | null)[];
  ingredients_original_tags: string[];
  allergens_tags: string[];
  allergens_from_ingredients: string;
  ingredients_from_or_that_may_be_from_palm_oil_n: number;
  stores_debug_tags: (string | null)[];
  categories: string;
  last_image_t: number;
  pnns_groups_1: string;
  product_quantity: number;
  emb_codes_debug_tags: (string | null)[];
  languages_codes: { country : number};
  pnns_groups_1_tags: string[];
  lang: string;
  image_front_small_url: string;
  nova_groups: string;
  informers: string[];
  nutrition_data_prepared_per: string;
  ingredients_text_fr_debug_tags: (string | null)[];
  last_editor: string;
  image_nutrition_small_url: string;
  ingredients_n_tags: string[];
  languages_tags: string[];
  expiration_date_debug_tags: (string | null)[];
  additives_prev_original_tags: (string | null)[];
  creator: string;
  vitamins_tags: string[];
  ingredients_text_fr: string;
  id: string;
  nutrition_score_warning_no_fruits_vegetables_nuts: number;
  nutrition_data_prepared_per_debug_tags: (string | null)[];
  lc: string;
  entry_dates_tags: string[];
  ingredients_text_with_allergens_fr: string;
  generic_name_fr_debug_tags: (string | null)[];
  nutrition_data: string;
  countries_hierarchy: string[];
  traces_tags: string[];
  states_hierarchy: string[];
  traces_from_ingredients: string;
  countries_lc: string;
  created_t: number;
  scans_n: number;
  emb_code: string;
  checkers: string[];
  last_modified_by: string;
  additives_prev_tags: string[];
  purchase_places_tags: string[];
  rev: number;
  categories_lc: string;
  serving_quantity: number;
  nutrient_levels: { nutrient : 'low' | 'moderate' | 'high' };
  manufacturing_places_debug_tags: (string | null)[];
  languages: { lang : number };
  minerals_tags: string[];
  additives_debug_tags: (string | null)[];
  editors: string[];
  emb_codes_20141016: string;
  stores_tags: string[];
  link_debug_tags: (string | null)[];
  nova_group_debug: string;
  emb_codes_orig: string;
  quantity: string;
  nova_group: string;
  nucleotides_tags: string[];
  purchase_places: string;
  ingredients_tags: string[];
  checkers_tags: string;
  pnns_groups_2: string;
  product_name_fr: string;
  brands: string;
  labels_lc: string;
  packaging: string;
  manufacturing_places: string;
  additives_tags: string[];
  additives_prev: string;
  nutrition_score_beverage: number;
  labels_prev_hierarchy: string[];
  unique_scans_n: number;
  labels_tags: string[];
  ingredients_ids_debug: string;
  sortkey: number;
  _id: string;
  serving_size_debug_tags: (string | null)[];
  ingredients_hierarchy: string[];
  labels_prev_tags: string[];
  link: string;
  new_additives_n: number;
  generic_name: string;
  nutrition_grade_fr: string;
  amino_acids_prev_tags: string[];
  last_modified_t: number;
  image_nutrition_url: string;
  cities_tags: string[];
  languages_hierarchy: string[];
  countries_debug_tags: (string | null)[];
  image_small_url: string;
  nova_groups_tags: string[];
  additives_n: number;
  vitamins_prev_tags: string[];
  complete: number;
  nutrition_grades: string;
  labels: string;
  nutrition_data_per_debug_tags: (string | null)[];
  categories_tags: string[];
  _keywords: string[];
  interface_version_modified: string;
  ingredients_from_palm_oil_tags: string[];
  debug_param_sorted_langs: string[];
  quality_tags: string[];
  labels_hierarchy: string[];
  ingredients_text: string;
  misc_tags: string[];
  traces_from_user: string;
  correctors: string[];
  amino_acids_tags: string[];
  nutrition_data_prepared: string;
  ingredients: object[];
  traces_hierarchy: string[];
  nutrition_score_debug: string[];
  lang_debug_tags: (string | null)[];
  origins_debug_tags: (string | null)[];
  traces: string[];
  image_ingredients_thumb_url: string;
  images: { name: object };
  nutrition_grades_tags: string[];
  image_nutrition_thumb_url: string;
  photographers: string[];
  packaging_tags: string[];
  brands_debug_tags: (string | null)[];
  additives: string;
  manufacturing_places_tags: string[];
  nucleotides_prev_tags: string[];
  image_ingredients_small_url: string;
}

export interface OpenFoodFactProductResponse {
  status_verbose: string;
  product: OpenFoodFactProduct;
  status: number;
  code: string;
}
